data:
    restart: always
    image: postgres
    volumes:
        - /var/lib/postgresql
    command: "true"

db:
    restart: always
    image: postgres
    volumes_from:
        - data
    ports:
        - "5432:5432"

web:
    restart: always
    image: mturki/karolin_web
    ports:
        - "8000:8000"
    volumes:
        - ./web:/karolin
    links:
        - db:db
    env_file:
        - .env
    command: ./entrypoint.sh
