data:
    restart: always
    image: postgres
    volumes:
        - /var/lib/postgresql
    command: "true"

db:
    restart: always
    image: postgres
    volumes_from:
        - data
    ports:
        - "5432:5432"

nginx:
    restart: always
    build: ./nginx
    ports:
        - "80:80"
    volumes:
        - ./web/static/:/var/www/karol.in/static/
    volumes_from:
        - web
    links:
        - web


web:
    restart: always
    build: ./web
    expose:
        - "8000"
    volumes:
        - ./web:/karolin
    links:
        - db:db
    env_file:
        - .env
    command: ./entrypoint.sh
