data:
    restart: always
    image: postgres
    volumes:
        - /var/lib/postgresql
    command: "true"

db:
    restart: always
    image: postgres
    volumes_from:
        - data
    ports:
        - "5432:5432"

nginx:
    restart: always
    image: mturki/karolin_nginx
    ports:
        - "80:80"
    volumes_from:
        - web
    links:
        - web


web:
    restart: always
    image: mturki/karolin_web
    expose:
        - "8000"
    volumes:
        # Mount the static dirs as a volume for nginx to pick up.
        - /var/www/karol.in/static/
        - /var/www/karol.in/media/
    links:
        - db:db
    command: ./entrypoint-production.sh
