# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20151128_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project categories'},
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
