# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
