# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
