# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20160216_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
